### ISSUE TITLE
load 官方python版bin classifier 报错

### ISSUE THREAD

**Issue by xikunlun001** [mayabot/fastText4j#16]
想请问下是否可以load 用facebook官方python接口训练出的bin classifier
我直接load 会报错：
Exception in thread "main" java.lang.RuntimeException: Model file has wrong file format!
	at com.mayabot.mynlp.fasttext.LoadFastTextFromClangModel.loadCModel(LoadFastTextFromClangModel.kt:32)
	at com.mayabot.mynlp.fasttext.LoadFastTextFromClangModel.loadCModel(LoadFastTextFromClangModel.kt:124)
	at com.mayabot.mynlp.fasttext.FastText$Companion.loadFasttextBinModel(FastText.kt:366)
	at com.mayabot.mynlp.fasttext.FastText.loadFasttextBinModel(FastText.kt)

**Comment by jimium** [comment]
```xml
<dependency>
  <groupId>com.mayabot.mynlp</groupId>
  <artifactId>fastText4j</artifactId>
  <version>3.1.0</version>
</dependency>
```
这个版本兼容最新的bin文件格式，你可以试试

**Comment by ares89** [comment]
使用了3.1.2依然报错哦

**Comment by jimium** [comment]
fix in 3.1.6
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
