### ISSUE TITLE
加载模型出错

### ISSUE THREAD

**Issue by yudian931122** [mayabot/fastText4j#26]
加载模型时，出现如下错误：
Exception in thread "main" java.lang.IllegalArgumentException: Unknown EntryType enum second :136
	at com.mayabot.nlp.fasttext.dictionary.EntryType$Companion.fromValue(DictUtils.kt:57)
	at com.mayabot.nlp.fasttext.dictionary.Dictionary$Companion.loadModel(Dictionary.kt:384)
	at com.mayabot.nlp.fasttext.FastText$Companion.loadModel(FastText.kt:711)
	at cn.com.duiba.spark.dmp.api.FasttextTest.loadModel(FasttextTest.java:61)
	at cn.com.duiba.spark.dmp.api.FasttextTest.main(FasttextTest.java:43)

求解

**Comment by jimium** [comment]
你记载的模型设是官方原版训练出来的还是通过java版本训练出来的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yudian931122 <notifications@github.com&gt;
发送时间: 2020年7月21日 18:57
收件人: mayabot/fastText4j <fastText4j@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[mayabot/fastText4j] 加载模型出错 (#26)

**Comment by yudian931122** [comment]
也是通过这个java版本训练出来的
刚才又训练一个数据量小一点，加载没问题
这是为啥呀

**Comment by yudian931122** [comment]
有办法吗？大佬 @jimichan

**Comment by jimium** [comment]
数据能不能发来我测试一下，把你的训练参数代码也给我看一下.

105287540@qq.com

**Comment by yudian931122** [comment]
> 数据能不能发来我测试一下，把你的训练参数代码也给我看一下.
> 
> [105287540@qq.com](mailto:105287540@qq.com)

数据不太方便给，见谅哈
目前猜测可能是某些特殊字符导致的这个问题，我用'[^\\u4E00-\\u9FFF]'正则去掉所有字符后，再训练模型是可以加载的
参数：
        InputArgs inputArgs = new InputArgs();
        inputArgs.setLoss(LossName.softmax);
        inputArgs.setLr(1D);
        inputArgs.setDim(100);
        inputArgs.setWordNgrams(3);
        inputArgs.setEpoch(25);

**Comment by jimium** [comment]
能解决就好
